# Generated by Django 3.2.3 on 2022-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image_url', models.CharField(max_length=2083)),
                ('category', models.CharField(choices=[('Starters', 'Starters'), ('Mains', 'Mains'), ('Beverages', 'Beverages'), ('Beverages', 'Beverages')], max_length=10)),
            ],
        ),
    ]
