# Generated by Django 3.2.3 on 2022-10-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Mains', 'Mains'), ('Beverages', 'Beverages'), ('Desserts', 'Desserts')], max_length=10),
        ),
    ]
