# Generated by Django 3.2.3 on 2022-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('starters', 'Starters'), ('mains', 'Mains'), ('beverages', 'Beverages'), ('desserts', 'Desserts')], max_length=10),
        ),
    ]
