# Generated by Django 3.2.3 on 2022-10-16 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_list',
        ),
    ]
